CREATE DATABASE mcdonalds;

USE mcdonalds;

CREATE TABLE PURCHASE_INFO (
	RecordID int PRIMARY KEY,
	ProductID varchar(255) NOT NULL,
	UserID varchar(255) NOT NULL,
	PurchaseTime datetime NOT NULL
);

CREATE TABLE PRODUCT_INFO (
	ProductID varchar(255) PRIMARY KEY,
	Name varchar(255) NOT NULL,
	ProductType varchar(255),
	Price int NOT NULL,
	IsAvailable BOOL NOT NULL
);

CREATE TABLE USER_INFO (
	UserID varchar(255) PRIMARY KEY,
	Name varchar(255) NOT NULL,
	Phone varchar(255) NOT NULL,
	IsMember BOOL NOT NULL
);

ALTER TABLE PURCHASE_INFO 
ADD CONSTRAINT fk_Product
FOREIGN KEY (ProductID) REFERENCES PRODUCT_INFO(ProductID);

ALTER TABLE PURCHASE_INFO 
ADD CONSTRAINT fk_User
FOREIGN KEY (UserID) REFERENCES USER_INFO(UserID);

INSERT INTO PRODUCT_INFO 
VALUES ('001', 'Hamburger', 'FOOD', 5, TRUE);

INSERT INTO PRODUCT_INFO 
VALUES ('002', 'Big-Mac', 'FOOD', 10, TRUE);

INSERT INTO PRODUCT_INFO 
VALUES ('003', 'Coke', 'DRINKS', 3, TRUE);
